# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
  use_frameworks!
target 'AFRModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AmazonFreeRTOS', :git => 'https://github.com/aws/amazon-freertos-ble-ios-sdk.git'

  # Pods for AFRModule

end
